# Copyright (C) 2018 Johann Lee <me@qinka.pro>
#
# This file is part of Haskell-FAI.
#
# Haskell-FAI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Haskell-FAI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Haskell-FAI. If not, see <http://www.gnu.org/licenses/>.
#

## Traivs-Ci configure
sudo: required
dist: trusty

## Matrix of building
env:
  - GHC_VER=8.2.2 THREADED=t LLVM=3.9 DEBUG=t RUN_TEST=t
  - GHC_VER=8.2.2            LLVM=3.9 DEBUG=t RUN_TEST=t
  - GHC_VER=8.2.2 THREADED=t          DEBUG=t RUN_TEST=t
  - GHC_VER=8.2.2                     DEBUG=t RUN_TEST=t

addons:
  apt:
    update: true
    sources:
      - hvr-ghc
    packages:
      - wget
      - curl
      - libgtest-dev
      - cmake
      - gcc
      - g++
      - make

before_install:
  - source $TRAVIS_BUILD_DIR/.travisci/init.sh

script:
  - source $TRAVIS_BUILD_DIR/.travisci/build.sh
  - source $TRAVIS_BUILD_DIR/.travisci/test.sh

after_success:
  - source $TRAVIS_BUILD_DIR/.travisci/after.sh

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/.travisci/deploy.sh
  
  

